"""Shared LBOE domain contracts."""

from .audit import (
    AuditAdapter,
    AuditArtifact,
    AuditEvidence,
    AuditFinding,
    AuditRequest,
    AuditResult,
    FakeAuditAdapter,
    WebsiteResolutionResult,
)
from .brief import (
    BusinessBriefFact,
    BusinessBriefOpportunity,
    BusinessBriefRecommendedAction,
    BusinessBriefRequest,
    BusinessBriefResult,
    BusinessBriefRisk,
    BusinessBriefSection,
)
from .demo import DemoArtifact, DemoClaim, DemoGenerationRequest, DemoQaResult, DemoSection, GeneratedDemo
from .discovery import (
    CandidateBusiness,
    DiscoveryAdapter,
    DiscoveryRequest,
    DiscoveryValidationError,
    IdentitySignals,
    identity_signals,
    normalize_domain,
    normalize_phone,
    normalize_text,
)
from .fakes import FakeDiscoveryAdapter
from .outreach import (
    OutreachDraftCheck,
    OutreachDraftEvidence,
    OutreachDraftMessage,
    OutreachDraftPackage,
    OutreachDraftRequest,
    OutreachOffer,
)
from .readiness import (
    OutreachChannelApproval,
    OutreachReadinessCheck,
    OutreachReadinessDecision,
    OutreachReadinessRequest,
    OutreachReadinessResult,
)
from .review import DemoReviewChecklist, DemoReviewNote, DemoReviewRequest, DemoReviewResult
from .scoring import (
    OpportunityScoreComponent,
    OpportunityScoreHold,
    OpportunityScoreRequest,
    OpportunityScoreResult,
    RecommendedNextAction,
    ScoreBand,
)
from .states import ALLOWED_TRANSITIONS, InvalidTransition, LeadState, transition, validate_transition

__all__ = [
    "ALLOWED_TRANSITIONS",
    "AuditAdapter",
    "AuditArtifact",
    "AuditEvidence",
    "AuditFinding",
    "AuditRequest",
    "AuditResult",
    "CandidateBusiness",
    "DiscoveryAdapter",
    "DiscoveryRequest",
    "DiscoveryValidationError",
    "FakeDiscoveryAdapter",
    "FakeAuditAdapter",
    "IdentitySignals",
    "InvalidTransition",
    "LeadState",
    "identity_signals",
    "normalize_domain",
    "normalize_phone",
    "normalize_text",
    "OpportunityScoreComponent",
    "OpportunityScoreHold",
    "OpportunityScoreRequest",
    "OpportunityScoreResult",
    "RecommendedNextAction",
    "ScoreBand",
    "BusinessBriefFact",
    "BusinessBriefOpportunity",
    "BusinessBriefRecommendedAction",
    "BusinessBriefRequest",
    "BusinessBriefResult",
    "BusinessBriefRisk",
    "BusinessBriefSection",
    "DemoArtifact",
    "DemoClaim",
    "DemoGenerationRequest",
    "DemoQaResult",
    "DemoSection",
    "GeneratedDemo",
    "DemoReviewChecklist",
    "DemoReviewNote",
    "DemoReviewRequest",
    "DemoReviewResult",
    "OutreachDraftCheck",
    "OutreachDraftEvidence",
    "OutreachDraftMessage",
    "OutreachDraftPackage",
    "OutreachDraftRequest",
    "OutreachOffer",
    "OutreachChannelApproval",
    "OutreachReadinessCheck",
    "OutreachReadinessDecision",
    "OutreachReadinessRequest",
    "OutreachReadinessResult",
    "WebsiteResolutionResult",
    "transition",
    "validate_transition",
]
