"""Lead lifecycle contract.

Sprint 1 should implement guarded transitions and persistence around these states.
"""
from enum import StrEnum


class LeadState(StrEnum):
    DISCOVERED = "DISCOVERED"
    DEDUPED = "DEDUPED"
    QUALIFIED = "QUALIFIED"
    REJECTED = "REJECTED"
    ENRICHING = "ENRICHING"
    ENRICHED = "ENRICHED"
    ENRICHMENT_FAILED = "ENRICHMENT_FAILED"
    AUDITING = "AUDITING"
    AUDITED = "AUDITED"
    SCORED = "SCORED"
    ARCHIVED = "ARCHIVED"
    DEMO_QUEUED = "DEMO_QUEUED"
    DEMO_GENERATED = "DEMO_GENERATED"
    QA_FAILED = "QA_FAILED"
    REVIEW_PENDING = "REVIEW_PENDING"
    APPROVED_FOR_OUTREACH = "APPROVED_FOR_OUTREACH"
    CONSENT_PENDING = "CONSENT_PENDING"
    OUTREACH_READY = "OUTREACH_READY"
    CONTACTED = "CONTACTED"
    REPLIED = "REPLIED"
    MEETING = "MEETING"
    PROPOSAL = "PROPOSAL"
    WON = "WON"
    LOST = "LOST"
    SUPPRESSED = "SUPPRESSED"
